configurations:
  project_name: my-cool-project
  random_seed: 42
  model_type: random_forest
  cross_validation_folds: 5
  test_size: 0.2
  early_stopping_rounds: 10

directories:
  raw_data_dir: data/raw
  processed_data_dir: data/processed
  models_dir: models
  outputs_dir: outputs
  logs_dir: outputs/logs

secrets:
  keys:
    - my-secret-01
    - my-secret-02

